# Generated by Django 3.2.12 on 2022-04-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField(blank=True, default=0, null=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('atomic_mass', models.FloatField(blank=True, default=0, null=True)),
                ('electronic_configuration', models.CharField(blank=True, default='', max_length=100)),
                ('electronegativity', models.FloatField(blank=True, default=0, null=True)),
                ('atomic_radius', models.IntegerField(blank=True, default=0, null=True)),
                ('ion_radius', models.CharField(blank=True, default='', max_length=100)),
                ('vanderwaalsradius', models.CharField(blank=True, default='', max_length=100)),
                ('ionization_energy', models.IntegerField(blank=True, default=0, null=True)),
                ('electron_afinity', models.IntegerField(blank=True, default=0, null=True)),
                ('oxidation_states', models.CharField(blank=True, default='', max_length=100)),
                ('standard_state', models.CharField(blank=True, default='', max_length=100)),
                ('bonding_type', models.CharField(blank=True, default='', max_length=100)),
                ('melting_point', models.IntegerField(blank=True, default=0, null=True)),
                ('boiling_point', models.IntegerField(blank=True, default=0, null=True)),
                ('density', models.FloatField(blank=True, default=0, null=True)),
                ('group_block', models.CharField(blank=True, default='', max_length=100)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
                ('cpx_hex_color', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.IntegerField(blank=True, default=0, null=True)),
                ('group', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
