# Generated by Django 3.2.12 on 2022-04-10 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='electron_afinity',
            new_name='electron_affinity',
        ),
    ]
