# Generated by Django 3.2.12 on 2022-04-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_rename_electron_afinity_element_electron_affinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='year_discovered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomic_mass',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
