# Generated by Django 3.2.12 on 2022-04-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20220410_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='year_discovered',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
